# Generated by Django 4.0.4 on 2022-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portrait',
            field=models.ImageField(default='profile/portrait/default.png', upload_to='profile/portrait/%Y%m%d/'),
        ),
    ]
