# Generated by Django 4.0.4 on 2022-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': 'confirm code', 'verbose_name_plural': 'confirm codes'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-c_time'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
