# Generated by Django 4.0.4 on 2022-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_confirmstring_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portrait',
            field=models.ImageField(blank=True, default='portrait/default.png', upload_to='portrait/%Y%m%d/'),
        ),
    ]
