# Generated by Django 4.0.4 on 2022-09-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_profile_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portrait',
            field=models.ImageField(blank=True, default='profile/portrait/default.png', upload_to='profile/portrait/%Y%m%d/'),
        ),
    ]
