# Generated by Django 4.0.4 on 2022-10-10 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='note',
            field=models.CharField(default="the author is lazy, didn't give any introduction", max_length=200),
        ),
        migrations.AddField(
            model_name='link',
            name='note',
            field=models.CharField(default="the author is lazy, didn't give any introduction", max_length=200),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 5, 46, 17, 468556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 5, 46, 17, 468556, tzinfo=utc)),
        ),
    ]
