# Generated by Django 4.0.4 on 2022-10-10 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_note_link_note_alter_maincategory_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='note',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(default="the author is lazy, didn't give any information", max_length=200),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 14, 58, 40, 214431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 14, 58, 40, 214431, tzinfo=utc)),
        ),
    ]
