# Generated by Django 4.0.4 on 2022-10-11 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_note_link_description_remove_file_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 18, 37, 14699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 18, 37, 15692, tzinfo=utc)),
        ),
    ]
