# Generated by Django 4.0.4 on 2022-09-27 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_article_author_alter_maincategory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 44, 42, 888908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 44, 42, 888908, tzinfo=utc)),
        ),
    ]
