# Generated by Django 4.0.4 on 2022-09-28 02:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_profile_portrait'),
        ('main', '0008_alter_maincategory_created_alter_subcategory_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='layne', on_delete=django.db.models.deletion.CASCADE, to='login.profile'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 2, 58, 36, 538112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 2, 58, 36, 538112, tzinfo=utc)),
        ),
    ]
