# Generated by Django 4.0.4 on 2022-09-30 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_maincategory_created_alter_subcategory_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 4, 53, 18, 724400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 4, 53, 18, 724400, tzinfo=utc)),
        ),
    ]
